---

- name: 'Install nginx'
  apt:
    name: nginx
    state: present

- name: 'Remove default config'
  file: 
    path: '/etc/nginx/sites-enabled/default'
    state: absent

- name: 'Copy vhosts'
  template:
    src: vhosts
    dest: "/etc/nginx/sites-enabled/{{ app_name }}.conf"
  notify: restart nginx

- name: 'Enable nginx'
  systemd:
    name: nginx
    enabled: yes
    state: started

