---

- name: 'Install deps'
  tags: 'mongodb'
  apt:
    name: python-pycurl
    update_cache: yes

- name: 'Add MongoDB repo key'
  tags: 'mongodb'
  apt_key:
    keyserver: '{{ repo_keyserver }}'
    id: '{{ repo_id }}'

- name: 'Add MongoDB repo'
  tags: 'mongodb'
  apt_repository:
    repo: '{{ repo }}'
    state: present
    filename: mongodb

- name: 'Install MongoDB'
  tags: 'mongodb'
  apt:
    name: mongodb-org
    update_cache: yes
    state: present

- name: 'Enable MongoDB service'
  tags: 'mongodb'
  service: 
    name: 'mongod'
    state: started
    enabled: yes

- name: 'Copy config file'
  tags: 'mongodb'
  template:
    src: 'mongod.conf.j2'
    dest: '/etc/mongod.conf'
    backup: 'yes'
  notify:
    - restart mongodb


